[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"
venv = "chat"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10.12"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src" }
]
